kumuluzee:
  name: collection-manager-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/CollectionManagerDS
      connection-url: jdbc:postgresql://host.docker.internal:5432/collection-manager
      username: dbuser
      password: postgres
      max-pool-size: 20
  dev:
    scan-libraries:
      - collection-manager-lib
  openapi-mp:
    enabled: true
    ui:
      enabled: true
      mapping: /openapi/ui
  metrics:
    servlet:
      enabled: true
      mapping: /metrics
    web-instrumentation:
      - name: collection-endpoint
        url-pattern: /v1/collection/*
        status-codes: "200, 201, 204, 400, 404, 409, 500"
      - name: tag-endpoint
        url-pattern: /v1/tag/*
        status-codes: "200, 201, 204, 400, 404, 409, 500"
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                        <Configuration name="comments">
                            <Appenders>
                                <Console name="console" target="SYSTEM_OUT">
                                    <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                                </Console>
                            </Appenders>
                            <Loggers>
                                <!-- Default logger -->
                                <Logger name="mtn.rso.pricecompare.collectionmanager" level="TRACE"/>
                                <Root level="info">
                                    <AppenderRef ref="console" level="trace" />
                                    <AppenderRef ref="logstash" level="trace" />
                                </Root>
                            </Loggers>
                        </Configuration>'
