kumuluzee:
  name: collection-manager-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/CollectionManagerDS
      connection-url: jdbc:postgresql://host.docker.internal:5432/collection-manager
      username: dbuser
      password: postgres
      max-pool-size: 20
  dev:
    scan-libraries:
      - collection-manager-lib
  openapi-mp:
    enabled: true
    ui:
      enabled: true
      mapping: /openapi/ui