kumuluzee:
  name: collection-manager-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8081
    http:
      port: 8081
  datasources:
    - jndi-name: jdbc/CollectionManagerDS
      connection-url: jdbc:postgresql://host.docker.internal:5433/collection-manager
      username: dbuser
      password: postgres
      max-pool-size: 20
  dev:
    scan-libraries:
      - collection-manager-lib
  openapi-mp:
    enabled: true
    ui:
      enabled: true
      mapping: /openapi/ui
  config:
    consul:
      agent: http://host.docker.internal:8500
  health:
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/CollectionManagerDS
  metrics:
    servlet:
      enabled: true
      mapping: /metrics
    web-instrumentation:
      - name: collection-endpoint
        url-pattern: /v1/collection/*
        status-codes: "200, 201, 204, 400, 404, 409, 500"
      - name: tag-endpoint
        url-pattern: /v1/tag/*
        status-codes: "200, 201, 204, 400, 404, 409, 500"
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                        <Configuration name="comments">
                            <Appenders>
                                <Console name="console" target="SYSTEM_OUT">
                                    <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                                </Console>
                                <Socket name="logstash" host="3a68956d-0567-4cd2-8ad3-bfda5f432292-ls.logit.io" port="23732" protocol="udp">
                                    <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                                </Socket>
                            </Appenders>
                            <Loggers>
                                <!-- Default logger -->
                                <Logger name="mtn.rso.pricecompare.collectionmanager" level="trace"/>
                                <Root level="info">
                                    <AppenderRef ref="console" level="trace" />
                                    <AppenderRef ref="logstash" level="trace" />
                                </Root>
                            </Loggers>
                        </Configuration>'

global-properties:
  app-liveness: true
  app-readiness: true

api-properties:
  verify-item-exists: true
  return-collection-item-information: true

client-properties:
  price-updater-host: host.docker.internal
  price-updater-port: 8080
